[package]
authors = ["ewillbefull@gmail.com"]
name = "pay-to-sudoku"
version = "0.0.1"

[dependencies.jsonrpc]
version = "0.7.1"
default-features = false

[dependencies]
unicase = "1.4.0"
bincode = "0.4.0"
bzip2 = "0.2.3"
clap = "1.5.4"
fixedbitset = "0.1.0"
flate2 = "0.2.11"
hex = "0.1.0"
libc = "0.2.2"
rand = "0.3.12"
serde = "0.6.6"
strason = "0.3.3"
whiteread = "0.2.0"
rust-crypto = "^0.2"
thread-scoped = "1.0.1"
